#=================================================
# ARQUIVO: docker-compose.yml
#=================================================
# Este arquivo orquestra o servi√ßo.

services:
  dsa_ai_agent_app:
    build: .
    container_name: terraform-dsa-ai-agent-containerizado
    ports:
      - "8505:8505"
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    restart: unless-stopped
